name: PR_unit_tests

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  Unit-test:
    name: Run unit tests on PR in master
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 20
      - name: Run detekt
        run: ./gradlew detekt

