name: Run detekt on each MR

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  Detekt:
    name: Run detekt on each MR
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 20
      - name: Run detekt
        run: ./gradlew detekt

